# Definição de variáveis (ambiente “local” do REST Client)
@base_url = https://curly-fiesta-5jq9q456p9vh76pv-5432.app.github.dev/

### Inserir novo veiculo
POST {{ base_url }}/api/veiculos
Content-Type: application/json

{
  "modelo": "Ford Ka",
  "ano": 2019,
  "valor": 40000
}

### Listar todos os veiculos
GET {{ base_url }}/api/veiculos
Accept: application/json

### Buscar veiculos por ID
GET {{ base_url }}/api/veiculos/1
Accept: application/json

### Atualizar veiculo (PUT)
PUT {{ base_url }}/api/veiculos/1
Content-Type: application/json

{
  "modelo": "Ford Ka",
  "ano": 2019,
  "valor" : 40000
}

### Remover pessoa (DELETE)
DELETE {{ base_url }}/api/veiculos/1
Accept: */*